app.controller("accounts", function ($scope) {
  console.log("Accounts Controller Initialized");

  $scope.accounts_columns = [
    { label: "#", type: "counter", field: "counter" },
    { label: "Full Name", type: "text", field: "name" },
    { label: "Designation", type: "text", field: "designation" },
  ];
  $scope.accounts_data = [
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
    { name: "Bryan Villarubia", designation: 'Admin' },
    { name: "Jemimah Villarubia", designation: 'Pharmacist' },
    { name: "Jemian Villarubia", designation: 'Registrar' },
  ];
  $scope.accounts_actions = [
    { icon: "fa fa-edit", iconSize: '15px', action: $scope.addBTN },
  ];
});
